portfolio/urls.py
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView
from drf_spectacular.views import SpectacularSwaggerView
import portfolio.views as views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet, basename='user')
router.register(r'groups', views.GroupViewSet, basename='group')
router.register(r'stocks', views.StockViewSet, basename='stock')
router.register(r'markets', views.MarketViewSet, basename='market')
router.register(r'accounts', views.AccountViewSet, basename='account')
router.register(r'portfolios', views.PortfolioViewSet, basename='portfolio')
router.register(r'transactions', views.TransactionViewSet, basename='transaction')
router.register(r'trades', views.TradeViewSet, basename='trade')
router.register(r'bulk-trades', views.BulkTradeViewSet, basename='bulk-trade')
router.register(r'dividends', views.DividendViewSet, basename='dividend')
router.register(r'holdings/(?P<portfolio_id>\d+)', views.HoldingsViewSet, basename='holdings')

app_name="portfolio"

urlpatterns = [
    path('overview', views.overview, name="portfolio-overview"),
    path('accounts', views.accounts, name="accounts-page"),
    path('portfolios', views.portfolios, name="portfolios-page"),
    path('<str:asset_type>/wallet', views.wallets, name="wallet-page"),
    path('<str:asset_type>/orders', views.orderbook, name="orders-page"),
    path('api/user/summary/', views.UserFinancialOverviewView.as_view(), name='net-worth'),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='portfolio:schema'), name='swagger'),
    path("api/", include((router.urls))),
    path("lander", views.temp, name="landing"),
]

urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name="core"

admin.autodiscover()

urlpatterns = [
    path("portfolio/", include("portfolio.urls"), name="portfolio-app"),
    path("admin/", admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path("", include("webui.urls")), 
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/views.py
from django.shortcuts import render
from django.contrib.auth.models import User, Group
from rest_framework import viewsets, permissions, filters
from rest_framework.response import Response
from rest_framework.filters import OrderingFilter
from rest_framework import status
from rest_framework.pagination import PageNumberPagination
from django_filters.rest_framework import DjangoFilterBackend
from portfolio.serializers import *
from datetime import timedelta, datetime

from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated

from django.contrib.auth.decorators import login_required

def temp(request):
    return render(request, "portfolio/lander.html", context={})

@login_required
def overview(request):
    enabled_modules = {'Stocks': {},
                       'Crypto': {},
                       'Commodity': {},
                       }
    context = {'entries': enabled_modules,
               'module': 'overview', }
    return render(request, "portfolio/render.html", context=context)

@login_required
def accounts(request):
    enabled_modules = {'Stocks': {},
                       'Crypto': {},
                       'Commodity': {},
                       }
    context = {'entries': enabled_modules,
               'module': 'accounts', }
    return render(request, "portfolio/render.html", context=context)

@login_required
def portfolios(request):
    enabled_modules = {'Stocks': {},
                       'Crypto': {},
                       'Commodity': {},
                       }
    context = {'entries': enabled_modules,
               'module': 'portfolios', }
    return render(request, "portfolio/render.html", context=context)

@login_required
def wallets(request, asset_type):
    enabled_modules = {'Stocks': {},
                       'Crypto': {},
                       'Commodity': {},
                       }
    context = {'entries': enabled_modules,
               'asset': asset_type,
               'module': 'wallet', }
    return render(request, "portfolio/render.html", context=context)

@login_required
def orderbook(request, asset_type):
    enabled_modules = {'Stocks': {},
                       'Crypto': {},
                       'Commodity': {},
                       }
    context = {'entries': enabled_modules,
               'asset': asset_type,
               'module': 'orders', }
    return render(request, "portfolio/render.html", context=context)

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]

class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited
    """
    queryset = Group.objects.all().order_by('id')
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]


class MarketViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows market objects to be viewed or edited
    """
    queryset = Market.objects.all().order_by('id')
    serializer_class = MarketSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    

class StockViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows market objects to be viewed or edited
    """
    queryset = Stock.objects.all().order_by('id')
    serializer_class = StockSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [filters.SearchFilter, DjangoFilterBackend]
    search_fields = ['symbol', 'market__name']  # Supports partial matching on these fields

    def get_queryset(self):
        queryset = self.queryset
        #print(self.request.query_params)
        symbol = self.request.query_params.get('symbol')
        market = self.request.query_params.get('market')
        
        if symbol:
            queryset = queryset.filter(symbol__contains=symbol)
        return queryset
    
class AccountViewSet(viewsets.ModelViewSet):
    queryset = Account.objects.all().order_by('id')
    serializer_class = AccountSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [DjangoFilterBackend, OrderingFilter]
    ordering_fields = '__all__'

    def partial_update(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
    
    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def get_serializer_context(self):
        # Pass the request context to the serializer
        return {'request': self.request}

class PortfolioViewSet(viewsets.ModelViewSet):
    queryset = Portfolio.objects.all().order_by('id')
    serializer_class = PortfolioSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [DjangoFilterBackend, OrderingFilter]
    ordering_fields = '__all__'

    def partial_update(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

class TransactionViewSet(viewsets.ModelViewSet):
    queryset = Transaction.objects.all().order_by('timestamp')
    serializer_class = TransactionSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [DjangoFilterBackend, OrderingFilter]
    ordering_fields = '__all__'
    filterset_fields = ['source_account', 'destination_account', 'transaction_type', 'timestamp']

    def get_queryset(self):
        queryset = self.queryset
        #print(self.request.query_params)
        account_id = self.request.query_params.get('account_id')
        date_start_filter = self.request.query_params.get('date_start')
        date_end_filter = self.request.query_params.get('date_end')
        
        if account_id:
            queryset = queryset.filter(source_account_id=account_id) | queryset.filter(destination_account_id=account_id)
        if date_start_filter:
            # Filter tasks by 'date_started'
            queryset = queryset.filter(timestamp__geq=date_start_filter)
        if date_end_filter:
            queryset = queryset.filter(timestamp__leq=date_end_filter)
        return queryset
    
    # def partial_update(self, request, *args, **kwargs):
    #     instance = self.get_object()
    #     serializer = self.get_serializer(instance, data=request.data, partial=True)
    #     serializer.is_valid(raise_exception=True)
    #     serializer.save()
    #     return Response(serializer.data)

class BulkTradeViewSet(viewsets.ModelViewSet):
    queryset = Trade.objects.all().order_by('timestamp')
    serializer_class = BulkTradeSerializer
    permission_classes = [permissions.IsAuthenticated]

    def create(self, request, *args, **kwargs):
        data = request.data
        serializer = self.get_serializer(data=data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return Response(serializer.data, status=status.HTTP_201_CREATED)

class TradeViewSet(viewsets.ModelViewSet):
    queryset = Trade.objects.all().order_by('timestamp')
    serializer_class = TradeSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly]
    filter_backends = [DjangoFilterBackend, OrderingFilter]
    ordering_fields = '__all__'

    filterset_fields = ['timestamp', 'portfolio', 'stock']

    def get_queryset(self):
        queryset = self.queryset
        #queryset = super().get_queryset()
        #print(self.request.query_params)
        date_start_filter = self.request.query_params.get('date_start')
        date_end_filter = self.request.query_params.get('date_end')
        portfolio_filter = self.request.query_params.get('portfolio_id')
        symbol = self.request.query_params.get('search')
        if date_start_filter:
            # Filter tasks by 'date_started'
            queryset = queryset.filter(timestamp__geq=date_start_filter)
        if date_end_filter:
            queryset = queryset.filter(timestamp__leq=date_end_filter)
        if portfolio_filter:
            queryset = queryset.filter(portfolio__id=portfolio_filter)
        if symbol:
            queryset = queryset.filter(stock__symbol__icontains=symbol)
        for q in queryset:
            print(q)
        return queryset
    
    def partial_update(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

class CustomPagination(PageNumberPagination):
    page_size = 150
    max_page_size = 500

class HoldingsViewSet(viewsets.ViewSet):
    serializer_class = HoldingSerializer
    filter_backends = [filters.SearchFilter, DjangoFilterBackend]
    search_fields = ['symbol', 'name']
    pagination_class = CustomPagination
    queryset = Portfolio.objects.none()  # Dummy queryset to satisfy permission check
    filterset_fields = ['timestamp', 'portfolio', 'symbol']

    def list(self, request, portfolio_id):
        portfolio = Portfolio.objects.get(id=portfolio_id)
        holdings = portfolio.get_portfolio()
        
        members = [{'stock': member[0], 'symbol':member[3], 'shares': member[1], 'price': member[2], 'cost': 0, 'cmp': member[4], 'value': 0, 'pnl': 0, 'day_change': 0} for member in holdings]
        members = sorted(members, key=lambda x: x['symbol'])
        # Apply search filtering
        symbol = request.query_params.get('symbol', None)

portfolio/templates/portfolio/accounts.html
{% extends "portfolio/base.html" %}
{% load render_bundle from webpack_loader %}

{% block content %}
    <main class="row overflow-auto">
        <div class="col pt-4">
            <div id="app" class="position-relative"></div>
            {% render_bundle 'accounts' %}
        </div>
    </main>
{% endblock content %}

portfolio/templates/portfolio/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block header %}
  <title>Findependence</title>
  {% endblock %}
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/custom.css' %} rel="stylesheet">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
  <link href="{% static 'css/fontawesome.css' %} rel="stylesheet" />
  <link href="{% static 'css/brands.css' %} rel="stylesheet" />
  <link href="{% static 'css/solid.css' %} rel="stylesheet" />
  <link rel="icon" type="image/x-icon" href="{% static 'images/findependence.ico' %}">
  <!-- <script src="{% static 'vendor-react.bundle.js' %}" defer="defer"></script> -->
</head>
<body>
  <div class="container-fluid overflow-hidden">
    <div class="row vh-100 overflow-auto">
        <div class="col-12 col-sm-3 col-xl-2 px-sm-2 px-0 bg-dark d-flex sticky-top">
            {% block sidebar %}
            <div class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
                <a href="/" class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5">Fin<span class="d-none d-sm-inline">dependence</span></span>
                </a>
                <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="{% url "portfolio:portfolio-overview" %}" class="nav-link px-sm-0 px-2">
                            <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                        </a>
                    </li>
                    <li>
                        <a href="#submenu0" data-bs-toggle="collapse" class="nav-link px-sm-0 px-2">
                            <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
                    </li>
                    <li>
                        <a href="{% url 'portfolio:accounts-page' %}" class="nav-link px-sm-0 px-2">
                            <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">Accounts</span></a>
                    </li>
                    <li>
                        <a href="{% url 'portfolio:portfolios-page' %}" class="nav-link px-sm-0 px-2">
                            <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">Portfolios</span></a>
                    </li>
                    {% for module in entries %}
                        <li>
                            <a href="#submenu{{ forloop.counter }}" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
                                <i class="fs-4 bi-bank2"></i> <span class="ms-1 d-none d-sm-inline">{{ module }}</span></a>
                            <ul class="collapse nav flex-column ms-1" id="submenu{{forloop.counter}}" data-bs-parent="#menu">
                                <li class="w-100">
                                    <a href="{% url 'portfolio:wallet-page' asset_type=module %}" class="nav-link px-0"><i class="fs-6 bi-wallet2"></i> <span class="d-none d-sm-inline">Wallet</span></a>
                                </li>
                                <li>
                                    <a href="{% url 'portfolio:orders-page' asset_type=module %}" class="nav-link px-0"><i class="fs-6 bi-list"></i> <span class="d-none d-sm-inline">Orders</span></a>
                                </li>
                                <li>
                                    <a href="#" class="nav-link px-0"><i class="fs-6 bi-cash"></i> <span class="d-none d-sm-inline">Taxes</span></a>
                                </li>
                            </ul>
                        </li>
                    {% endfor %}
                    <li>
                        <a href="#" class="nav-link px-sm-0 px-2">
                            <i class="fs-5 bi-grid"></i><span class="ms-1 d-none d-sm-inline">Analysis</span></a>
                    </li>
                    <li>
                        <a href="#" class="nav-link px-sm-0 px-2">
                            <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">Trends</span> </a>
                    </li>
                </ul>
                <div class="dropdown py-sm-4 mt-sm-auto ms-auto ms-sm-0 flex-shrink-1">
                    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://avatars.githubusercontent.com/u/3250225?v=4" alt="hugenerd" width="28" height="28" class="rounded-circle">
                        <span class="d-none d-sm-inline mx-1">Anshul</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <form method="post" action="{% url 'logout' %}" style="display: inline;">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item">
                                    Sign out
                                </button>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
            {% endblock sidebar %}
        </div>
        <div class="col d-flex flex-column h-sm-100">
            {% block content %}
            <main class="row overflow-auto">
                <div class="col pt-4">
                    <h3>Findependence</h3>
                </div>
            </main>
            {% endblock content %}

            {% block footer %}
            <footer class="row bg-light py-4 mt-auto">
                <div class="col"> Footer content here... </div>
            </footer>
            {% endblock footer %}
        </div>
    </div>
  </div>
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>

portfolio/templates/portfolio/overview.html
{% extends "portfolio/base.html" %}
{% load render_bundle from webpack_loader %}

{% block content %}
    <main class="row overflow-auto">
        <div class="col pt-4">
            <div id="app"></div>
            {% render_bundle 'overview' %}
        </div>
    </main>
{% endblock content %}

portfolio/templates/portfolio/render.html
{% extends "portfolio/base.html" %}
{% load render_bundle from webpack_loader %}

{% block content %}
    <script type="text/javascript">
        // Make the CSRF token available as a JavaScript variable
        const csrftoken = "{{ csrf_token }}";
    </script>
    <main class="row overflow-auto">
        <div class="col pt-4">
            <div id="app" class="position-relative"></div>
            {% render_bundle module %}
        </div>
    </main>
{% endblock content %}

portfolio/templates/portfolio/wallet.html
{% extends "portfolio/base.html" %}
{% load render_bundle from webpack_loader %}

{% block content %}
    <main class="row overflow-auto">
        <div class="col pt-4">
            <div id="app" class="position-relative"></div>
            {% render_bundle 'wallet' %}
        </div>
    </main>
{% endblock content %}